### ISSUE TITLE
Lesson 06 - Positioning Content

### ISSUE THREAD

**Issue by andremaldonado** [andremaldonado/frontend-wannabe#12]
## What is it
Study this lesson [Positioning Content](https://learn.shayhowe.com/html-css/positioning-content/)

### Tasks - Part one
 - [x] Add clearfix to CSS
 - [x] Float the header
 - [x] Format the logo
 - [x] Add clearfix to the header
 - [x] Add clearfix to the footer
 - [x] Float the footer in CSS
 - [x] Add some padding to the footer

### Tasks - Part Two
 - [x] Add CSS for columns
 - [x] Fix container style
 - [x] Align teasers in columns

### Any references?
None
